import { Bot, CheckCircle2, Code2, Compass, Layers3, Palette, ShieldCheck, Sparkles, Wand2 } from "lucide-react";
import { Link } from "wouter";
import AcademyHeader from "@/components/AcademyHeader";
import PhoenixFlame from "@/components/PhoenixFlame";
import { Button } from "@/components/ui/button";

const curriculumHeroImage = "/manus-storage/phoennixai-curriculum-hero_d6b332ab.jpg";

const academyPathways = [
  { icon: Compass, title: "Foundations and exploration", copy: "Junior pathways begin with confident experimentation across product design, coding, gaming, graphics, and digital creativity." },
  { icon: Layers3, title: "Creative and technical practice", copy: "Learners develop live project skills in UI and UX, software computing, content creation, digital marketing, and AI automation." },
  { icon: CheckCircle2, title: "Professional and founder outcomes", copy: "Advanced learners turn their growing skills into a portfolio, practical capability, and a credible next-step pathway." },
];

const agencyCapabilities = [
  { icon: Compass, title: "Product strategy", copy: "Feature scoping, product-roadmap thinking, and MVP-definition support." },
  { icon: Palette, title: "UI and UX design", copy: "Wireframes, prototypes, and pitch-ready visual design for digital products." },
  { icon: Code2, title: "Engineering support", copy: "Technical build support and review for founders with working or near-working products." },
  { icon: ShieldCheck, title: "Quality assurance", copy: "Testing and quality review before a product is presented to users or investors." },
  { icon: Bot, title: "AI automation", copy: "Automation workflows and practical AI implementation that make teams more capable and efficient." },
];

export default function Curriculum() {
  return <div className="min-h-screen bg-[#F7F6F2] text-[#1F2426] dark:bg-[#0D1520] dark:text-[#F7F6F2]"><AcademyHeader /><main><section className="relative overflow-hidden bg-[#0D1520] py-20 text-white sm:py-28"><div aria-hidden="true" className="academy-hero-image absolute inset-0 bg-cover bg-[70%_center]" style={{ backgroundImage: `url(${curriculumHeroImage})` }} /><div aria-hidden="true" className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,18,29,.93)_0%,rgba(8,18,29,.8)_42%,rgba(8,18,29,.43)_100%)]" /><div className="phoenix-grid absolute inset-0" /><div className="absolute right-[8%] top-12 h-64 w-64 rounded-full border border-[#42B4E7]/25" /><div className="container relative max-w-5xl"><div className="flex items-center gap-3"><PhoenixFlame className="h-9 w-9 text-[#42B4E7]" /><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#C5F0FF]">PhoennixAI curriculum specification</p></div><h1 className="mt-7 font-display text-6xl font-bold leading-[.84] tracking-wide sm:text-8xl">Learn. Build. <span className="text-[#C9C877]">Launch.</span></h1><p className="mt-7 max-w-3xl font-body text-xl leading-8 text-[#E5F5FA]">PhoennixAI brings together an Academy for capability-building and an Agency for technology, automation, and product execution. The curriculum is designed to help learners understand, apply, and scale the skills that matter.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild className="rounded-md bg-[#ABA944] font-mono text-[10px] uppercase tracking-[0.1em] text-[#1F2426] hover:bg-[#C9C877]"><Link href="/apply">Find your pathway</Link></Button><Button asChild variant="outline" className="rounded-md border-white/25 bg-white/5 font-mono text-[10px] uppercase tracking-[0.1em] text-white hover:bg-white/10 hover:text-white"><Link href="/rise-to-capital">View Rise to Capital</Link></Button></div></div></section>
    <section className="py-20 sm:py-28"><div className="container"><div className="max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">PhoennixAI Academy</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">A curriculum for future builders.</h2><p className="mt-5 font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">The Academy’s CPD-approved certification pathways help learners progress from exploration to practical capability and confident professional outcomes.</p></div><div className="mt-11 grid gap-4 lg:grid-cols-3">{academyPathways.map(({ icon: Icon, title, copy }) => <article key={title} className="rounded-lg border border-[#556970]/18 bg-white p-7 shadow-sm dark:bg-[#172231]"><Icon className="h-7 w-7 text-[#42B4E7]" /><h3 className="mt-8 font-display text-3xl font-bold tracking-wide">{title}</h3><p className="mt-3 font-body leading-7 text-[#526269] dark:text-[#D0DEE1]">{copy}</p></article>)}</div></div></section>
    <section className="bg-[#EFF0EA] py-20 dark:bg-white/[0.035] sm:py-28"><div className="container grid gap-8 lg:grid-cols-[.78fr_1.22fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">PhoennixAI Agency</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">Technology and automation that make ideas real.</h2><p className="mt-5 font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">The Agency connects learning to execution through practical product, design, engineering, quality, and automation capability for founders and teams.</p><div className="mt-8 flex items-center gap-3 border-l-2 border-[#42B4E7] pl-5"><Wand2 className="h-5 w-5 text-[#1688B8]" /><p className="font-body text-[#526269] dark:text-[#D0DEE1]">From a clear opportunity to a stronger product and more capable operation.</p></div></div><div className="grid gap-3 sm:grid-cols-2">{agencyCapabilities.map(({ icon: Icon, title, copy }) => <article key={title} className="rounded-lg border border-[#556970]/18 bg-white p-5 transition-transform duration-200 hover:-translate-y-1 dark:bg-[#172231]"><Icon className="h-5 w-5 text-[#42B4E7]" /><h3 className="mt-5 font-display text-2xl font-bold tracking-wide">{title}</h3><p className="mt-2 font-body leading-6 text-[#526269] dark:text-[#D0DEE1]">{copy}</p></article>)}</div></div></section>
    <section className="py-20 sm:py-28"><div className="container grid gap-8 rounded-lg bg-[#142833] p-8 text-white sm:p-12 lg:grid-cols-[1.1fr_.9fr]"><div><Sparkles className="h-7 w-7 text-[#42B4E7]" /><p className="mt-8 font-mono text-[10px] uppercase tracking-[0.16em] text-[#C5F0FF]">One connected ecosystem</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide">Skills, technology, and venture readiness in one place.</h2></div><div className="flex flex-col justify-center"><p className="font-body text-lg leading-8 text-[#E5F5FA]">Whether a learner is discovering a first skill, developing professional confidence, or preparing a venture to raise capital, PhoennixAI offers a connected progression path.</p><Button asChild className="mt-7 w-fit rounded-md bg-[#ABA944] font-mono text-[10px] uppercase tracking-[0.1em] text-[#1F2426] hover:bg-[#C9C877]"><Link href="/apply">Start your enquiry</Link></Button></div></div></section>
  </main></div>;
}
