import { useEffect } from "react";
import { CalendarDays, CheckCircle2, Compass, Facebook, Instagram, Linkedin, MapPin, Twitter } from "lucide-react";
import { Link } from "wouter";
import AcademyHeader from "@/components/AcademyHeader";
import CourseCard from "@/components/CourseCard";
import PhoenixFlame from "@/components/PhoenixFlame";
import VisitorChat from "@/components/VisitorChat";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { useLiveCatalog } from "@/hooks/useLiveCatalog";

const HERO_IMAGE = "/manus-storage/academy-studio-hero_8bd2bb43.jpg";
const MANDATE_IMAGE = "/manus-storage/academy-mandate_4ca25858.jpg";
const PROJECT_IMAGE = "/manus-storage/academy-project-learning_baf16fd7.jpg";
const INNOVATION_IMAGE = "/manus-storage/academy-innovation_05cc55e6.jpg";
const EVENTS_IMAGE = "/manus-storage/academy-events-brochure_8e1c8429.jpg";
const PHOENIX_LOGO = "/manus-storage/phoennixai-phoenix-logo_7d43347d.jpg";

function usePageView(path: string) { const track = trpc.academy.trackPageView.useMutation(); useEffect(() => { const key = "phoennixai-visitor"; const visitorKey = sessionStorage.getItem(key) ?? crypto.randomUUID(); sessionStorage.setItem(key, visitorKey); track.mutate({ path, visitorKey }); }, [path]); }

function SocialLink({ href, label, icon: Icon }: { href?: string; label: string; icon: typeof Instagram }) { return <a href={href || "#"} onClick={event => { if (!href) event.preventDefault(); }} aria-label={label} title={href ? label : `${label} link can be added in Admin`} className="group grid h-9 w-9 place-items-center rounded-md border border-[#556970]/20 text-[#526269] transition-[transform,color,background-color,border-color,box-shadow] duration-200 hover:-translate-y-1 hover:scale-110 hover:border-[#42B4E7] hover:bg-[#42B4E7]/15 hover:text-[#1688B8] hover:shadow-[0_8px_18px_rgba(66,180,231,.2)] focus-visible:-translate-y-1 focus-visible:scale-110 focus-visible:border-[#42B4E7] focus-visible:bg-[#42B4E7]/15 focus-visible:text-[#1688B8] focus-visible:shadow-[0_0_0_3px_rgba(66,180,231,.25)] focus-visible:outline-none dark:text-[#D1E8EF]"><Icon className="h-4 w-4 transition-transform duration-200 group-hover:rotate-[-8deg] group-focus-visible:rotate-[-8deg]" /></a>; }

export default function Home() {
  useLiveCatalog(); const { data } = trpc.academy.catalog.useQuery(undefined, { refetchInterval: 15000 }); usePageView("/");
  const content = data?.content ?? {}; const courses = data?.courses ?? []; const featured = courses.find(course => course.featured) ?? courses[0]; const events = data?.events ?? [];
  return <div className="min-h-screen overflow-hidden bg-[#F7F6F2] text-[#1F2426] dark:bg-[#0D1520] dark:text-[#F7F6F2]"><AcademyHeader /><main>
    <section className="relative isolate overflow-hidden bg-[#0D1520] text-white"><img src={HERO_IMAGE} alt="PhoennixAI learning studio" className="absolute inset-0 h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(13,21,32,.98)_0%,rgba(13,21,32,.84)_48%,rgba(13,21,32,.47)_100%)]" /><div className="brand-grid absolute inset-0 opacity-45" /><div className="absolute -right-28 top-14 h-80 w-80 rounded-full border border-[#42B4E7]/25" /><div className="orbital absolute right-[12%] top-24 h-32 w-32 rounded-full border border-[#42B4E7]/35" />
      <div className="container relative grid min-h-[650px] items-end gap-10 py-20 sm:py-24 lg:grid-cols-[1.05fr_.95fr] lg:py-28"><div className="reveal max-w-3xl"><p className="font-mono text-[10px] font-medium uppercase tracking-[0.18em] text-[#C9C877]">{content.hero_eyebrow ?? "Purpose-led skills for tomorrow’s builders"}</p><p className="mt-4 font-mono text-[9px] uppercase tracking-[0.14em] text-white/60">Business &amp; Technology Centre</p><h1 className="mt-5 max-w-3xl font-display text-6xl font-bold leading-[.86] tracking-wide text-balance sm:text-7xl lg:text-8xl">{content.hero_title ?? "Building capable futures through business, technology & purpose."}</h1><p className="mt-7 max-w-xl font-body text-lg leading-8 text-[#EFF0EA]">{content.hero_description ?? "Live, project-led learning for children, teens, and adults ready to build with clarity, confidence, and conviction."}</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="rounded-md bg-[#ABA944] px-5 font-mono text-[10px] uppercase tracking-[0.1em] text-[#1F2426] hover:bg-[#C9C877]"><Link href="/apply">Begin enquiry</Link></Button><Button asChild size="lg" variant="outline" className="rounded-md border-white/25 bg-white/5 font-mono text-[10px] uppercase tracking-[0.1em] text-white hover:bg-white/10 hover:text-white"><Link href="/courses">Explore programmes</Link></Button></div></div>
        <div className="reveal-delay relative self-center lg:self-end"><div className="absolute -inset-6 rounded-full bg-[#42B4E7]/10 blur-3xl" /><div className="relative ml-auto max-w-sm border border-[#42B4E7]/45 bg-[#0D1520]/80 p-6 backdrop-blur-md"><div className="flex items-center justify-between"><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#C9C877]">The academy principle</p><PhoenixFlame className="h-7 w-7 text-[#42B4E7]" /></div><p className="mt-10 font-body text-2xl leading-tight text-[#F7F6F2]">Skills that become solutions. Purpose that becomes legacy.</p><div className="mt-10 grid grid-cols-3 border-t border-white/15 pt-4 text-center"><div><p className="font-display text-3xl font-bold text-[#C9C877]">8+</p><p className="mt-1 font-mono text-[8px] uppercase tracking-wider text-white/55">Prep school</p></div><div className="border-x border-white/15"><p className="font-display text-3xl font-bold text-[#C9C877]">6–8</p><p className="mt-1 font-mono text-[8px] uppercase tracking-wider text-white/55">Months guided</p></div><div><p className="font-display text-3xl font-bold text-[#C9C877]">Live</p><p className="mt-1 font-mono text-[8px] uppercase tracking-wider text-white/55">Mentorship</p></div></div></div></div>
      </div>
    </section>
    <section id="mandate" className="py-20 sm:py-28"><div className="container grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div className="reveal"><p className="font-mono text-[10px] font-medium uppercase tracking-[0.16em] text-[#8A8835]">Our mandate</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">More than education.</h2><p className="mt-5 max-w-md font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">An environment where gifts are discovered, activated, and applied to meaningful work.</p><div className="mt-8 overflow-hidden rounded-lg border border-[#556970]/15"><img src={MANDATE_IMAGE} alt="PhoennixAI community and mentorship" className="h-56 w-full object-cover transition-transform duration-700 hover:scale-105" /></div></div><div className="reveal-delay self-center border-l-2 border-[#ABA944] pl-7 sm:pl-10"><blockquote className="font-body text-3xl leading-tight text-[#3D4447] dark:text-[#EFF0EA] sm:text-4xl">“{content.mandate ?? "At PhoennixAI, we don't raise followers - we raise leaders and builders. We remind every learner that you're kings, not servants - owners, you're created to create."}”</blockquote><p className="mt-7 font-mono text-[10px] uppercase tracking-[0.13em] text-[#8A8835]">Excellence · Integrity · Impact</p></div></div></section>
    <section className="relative overflow-hidden bg-[#EFF0EA] py-20 dark:bg-white/[0.035] sm:py-28"><div className="container"><div className="reveal flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">Learn by building</p><h2 className="mt-3 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">Practical pathways for every stage.</h2></div><Button asChild variant="outline" className="w-fit rounded-md border-[#556970]/35 font-mono text-[10px] uppercase tracking-[0.1em] text-[#556970] hover:bg-[#556970] hover:text-white"><Link href="/courses">View all programmes</Link></Button></div><div className="mt-10 grid gap-4 md:grid-cols-3">{courses.filter(course => !course.featured).slice(0, 3).map((course, index) => <article key={course.id} className={`reveal rounded-lg border border-[#556970]/22 bg-white p-6 shadow-sm transition-transform duration-300 hover:-translate-y-1 ${index === 1 ? "reveal-delay" : index === 2 ? "reveal-delay-2" : ""}`}><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#526269]">{course.duration}</p><h3 className="mt-7 font-display text-3xl font-bold leading-none tracking-wide">{course.title}</h3><p className="mt-4 font-body leading-7 text-[#425156]">{course.description}</p><Link href="/apply" className="mt-7 inline-flex items-center font-mono text-[10px] uppercase tracking-[0.12em] text-[#3E4F55] hover:text-[#1688B8]">Explore route</Link></article>)}</div></div></section>
    {featured ? <section className="py-20 sm:py-28"><div className="container grid gap-9 lg:grid-cols-[.8fr_1.2fr]"><div className="reveal flex flex-col justify-center"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">Designed for households</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">A practical start, without the pressure.</h2><p className="mt-5 max-w-sm font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">Our family pathway makes structured learning more accessible while allowing families to retain flexibility.</p><div className="mt-8 overflow-hidden rounded-lg"><img src={PROJECT_IMAGE} alt="Students working on project-led learning" className="h-56 w-full object-cover" /></div></div><div className="reveal-delay"><CourseCard course={featured} /></div></div></section> : null}
    <section id="events" className="relative isolate overflow-hidden bg-[#142833] py-20 text-white sm:py-28"><img src={EVENTS_IMAGE} alt="PhoennixAI Academy event gathering" className="absolute inset-0 h-full w-full object-cover opacity-28" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(20,40,51,.98)_0%,rgba(20,40,51,.88)_50%,rgba(20,40,51,.48)_100%)]" /><div className="phoenix-grid absolute inset-0" /><div className="container relative grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="reveal"><div className="flex items-center gap-3"><PhoenixFlame className="h-9 w-9 text-[#42B4E7]" /><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#C5F0FF]">Gather, learn, build</p></div><h2 className="mt-5 font-display text-6xl font-bold leading-[.86] tracking-wide sm:text-7xl">Upcoming events.</h2><p className="mt-6 max-w-md font-body text-lg leading-8 text-[#E5F5FA]">Workshops, showcases, and conversations for the next generation of builders. Each event has its own learning purpose and public Luma registration page.</p></div><div className="grid gap-4">{events.length ? events.map(event => <article key={event.id} className="reveal border border-[#42B4E7]/25 bg-[#0D1520]/55 p-6 backdrop-blur-sm"><p className="font-mono text-[10px] uppercase tracking-[0.13em] text-[#A8E6FF]">{event.eventDate}</p><h3 className="mt-5 font-display text-4xl font-bold leading-none tracking-wide">{event.title}</h3><p className="mt-4 max-w-xl font-body text-lg leading-7 text-[#EFF8FB]">{event.summary}</p><a href={event.lumaUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center font-mono text-[10px] uppercase tracking-[0.12em] text-[#A8E6FF] hover:text-white">View event on Luma</a></article>) : <article className="reveal border border-[#42B4E7]/25 bg-[#0D1520]/55 p-6 backdrop-blur-sm"><CalendarDays className="h-7 w-7 text-[#42B4E7]" /><h3 className="mt-5 font-display text-4xl font-bold leading-none tracking-wide">Events are being prepared.</h3><p className="mt-4 max-w-xl font-body text-lg leading-7 text-[#EFF8FB]">The next workshop and showcase will be published here as soon as the Academy team adds it through the Admin Management Centre.</p></article>}</div></div></section>
    <section className="py-20 sm:py-28"><div className="container grid gap-8 lg:grid-cols-[.95fr_1.05fr]"><div className="reveal"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">Innovation in practice</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">Courage to imagine. Discipline to build.</h2><p className="mt-5 max-w-lg font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">We fuse human creativity, emerging technologies, and project-led learning to help learners turn potential into work that matters.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{[[Compass, "Design thinking", "Rapid prototyping and iteration."],[CheckCircle2, "Portfolio outcomes", "Ideas shaped into real work."]].map(([Icon, title, copy]) => { const IconComponent = Icon as typeof Compass; return <div key={title as string} className="border-t border-[#556970]/20 pt-4"><IconComponent className="h-5 w-5 text-[#42B4E7]" /><h3 className="mt-4 font-display text-2xl font-bold tracking-wide">{title as string}</h3><p className="mt-2 font-body text-[#526269] dark:text-[#B3B9BA]">{copy as string}</p></div>})}</div></div><div className="reveal-delay overflow-hidden rounded-lg border border-[#556970]/15"><img src={INNOVATION_IMAGE} alt="Innovation and collaborative studio culture" className="h-full min-h-96 w-full object-cover" /></div></div></section>
  </main><footer className="border-t border-[#556970]/15 bg-white py-14 text-[#3D4447] dark:bg-[#0D1520] dark:text-[#EFF0EA]"><div className="container grid gap-10 md:grid-cols-[1.25fr_.8fr_.9fr]"><div><div className="flex items-center gap-3"><span className="grid h-11 w-11 overflow-hidden rounded-full border-2 border-[#42B4E7]/70 bg-[#0D1520]"><img src={PHOENIX_LOGO} alt="PhoennixAI phoenix" className="h-full w-full scale-[1.35] object-cover object-[50%_28%]" /></span><div><p className="font-display text-3xl font-bold tracking-wide">Phoenn<span className="text-[#1688B8]">ix</span>AI</p><p className="mt-0.5 font-mono text-[9px] uppercase tracking-[0.13em] text-[#526269]">Academy</p></div></div><p className="mt-5 max-w-sm font-body leading-7 text-[#526269] dark:text-[#B3B9BA]">Purpose-led learning for future builders, leaders, and innovators.<br /><span className="font-semibold text-[#1688B8] dark:text-[#A8E6FF]">You’re Created to Create.</span></p><div className="mt-6 flex gap-2"><SocialLink label="Instagram" href={content.social_instagram} icon={Instagram} /><SocialLink label="LinkedIn" href={content.social_linkedin} icon={Linkedin} /><SocialLink label="X" href={content.social_x} icon={Twitter} /><SocialLink label="Facebook" href={content.social_facebook} icon={Facebook} /></div></div><div><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#8A8835]">Navigate</p><div className="mt-4 grid gap-2.5 font-body"><Link href="/" className="hover:text-[#1688B8]">Home</Link><Link href="/courses" className="hover:text-[#1688B8]">Programmes</Link><Link href="/apply" className="hover:text-[#1688B8]">Student enquiry</Link><a href="#events" className="hover:text-[#1688B8]">Events</a></div></div><div><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#8A8835]">Contact</p><div className="mt-4 space-y-3 font-body text-[#526269] dark:text-[#B3B9BA]"><p className="flex gap-2"><MapPin className="mt-1 h-4 w-4 shrink-0 text-[#42B4E7]" />{content.footer_address ?? "58 Peregrine Road, Essex, IG6 3SZ"}</p><a className="block hover:text-[#1688B8]" href="mailto:info@phoennixai.com">info@phoennixai.com</a><p>Mon–Fri · 08:00–18:00 UK Time</p></div></div></div><div className="container mt-12 border-t border-[#556970]/15 pt-5 font-mono text-[8px] uppercase tracking-[0.12em] text-[#9BA4A7]">© {new Date().getFullYear()} PhoennixAI. All rights reserved.</div></footer><VisitorChat /></div>;
}
