import { useEffect } from "react";
import { CalendarDays, CheckCircle2, Compass } from "lucide-react";
import { Link } from "wouter";
import AcademyHeader from "@/components/AcademyHeader";
import CourseCard from "@/components/CourseCard";
import PhoenixFlame from "@/components/PhoenixFlame";
import PartnerStrip from "@/components/PartnerStrip";
import VisitorChat from "@/components/VisitorChat";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { useLiveCatalog } from "@/hooks/useLiveCatalog";

const HERO_IMAGE = "/manus-storage/phoennixai-academy-hero_9e615f29.jpg";
const MANDATE_IMAGE = "/manus-storage/phoennixai-mandate-leaders_c2451ab3.jpg";
const PROJECT_IMAGE = "/manus-storage/phoennixai-family-seasonal-creative_14169666.jpg";
const INNOVATION_IMAGE = "/manus-storage/academy-innovation_05cc55e6.jpg";
const EVENTS_IMAGE = "/manus-storage/phoennixai-events-gala_3a4c077a.jpg";

function usePageView(path: string) { const track = trpc.academy.trackPageView.useMutation(); useEffect(() => { const key = "phoennixai-visitor"; const visitorKey = sessionStorage.getItem(key) ?? crypto.randomUUID(); sessionStorage.setItem(key, visitorKey); track.mutate({ path, visitorKey }); }, [path]); }
function useHomeAnchor() { useEffect(() => { let timers: number[] = []; const revealAnchor = () => { timers.forEach(window.clearTimeout); timers = []; const id = window.location.hash.slice(1); if (!id) return; [0, 120, 420, 900].forEach(delay => timers.push(window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: "auto", block: "start" }), delay))); }; revealAnchor(); window.addEventListener("hashchange", revealAnchor); return () => { timers.forEach(window.clearTimeout); window.removeEventListener("hashchange", revealAnchor); }; }, []); }

export default function Home() {
  useLiveCatalog(); useHomeAnchor(); const { data } = trpc.academy.catalog.useQuery(undefined, { refetchInterval: 15000 });
  const content = data?.content ?? {}; const courses = data?.courses ?? []; const featured = courses.find(course => course.slug === "holiday-family-bundle") ?? courses.find(course => course.featured) ?? courses[0]; const events = data?.events ?? [];
  return <div className="min-h-screen overflow-hidden bg-[#F7F6F2] text-[#1F2426] dark:bg-[#0D1520] dark:text-[#F7F6F2]"><AcademyHeader /><main>
    <section className="relative isolate overflow-hidden bg-[#0D1520] text-white"><img src={HERO_IMAGE} alt="PhoennixAI learning studio" className="academy-hero-image absolute inset-0 h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(13,21,32,.98)_0%,rgba(13,21,32,.84)_48%,rgba(13,21,32,.47)_100%)]" /><div className="brand-grid absolute inset-0 opacity-45" /><div className="absolute -right-28 top-14 h-80 w-80 rounded-full border border-[#42B4E7]/25" /><div className="orbital absolute right-[12%] top-24 h-32 w-32 rounded-full border border-[#42B4E7]/35" />
      <div className="container relative grid min-h-[650px] items-end gap-10 py-20 sm:py-24 lg:grid-cols-[1.05fr_.95fr] lg:py-28"><div className="reveal max-w-3xl"><p className="font-mono text-[10px] font-medium uppercase tracking-[0.18em] text-[#C9C877]">{content.hero_eyebrow ?? "Purpose-led skills for tomorrow’s builders"}</p><p className="mt-4 font-mono text-[9px] uppercase tracking-[0.14em] text-white/60">Business &amp; Technology Centre</p><h1 className="mt-5 max-w-3xl font-display text-6xl font-bold leading-[.86] tracking-wide text-balance sm:text-7xl lg:text-8xl">{content.hero_title ?? "Building capable futures through business, technology & purpose."}</h1><p className="mt-7 max-w-xl font-body text-lg leading-8 text-[#EFF0EA]">{content.hero_description ?? "Live, project-led learning for children, teens, and adults ready to build with clarity, confidence, and conviction."}</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="rounded-md bg-[#ABA944] px-5 font-mono text-[10px] uppercase tracking-[0.1em] text-[#1F2426] hover:bg-[#C9C877]"><Link href="/apply">Begin enquiry</Link></Button><Button asChild size="lg" variant="outline" className="rounded-md border-white/25 bg-white/5 font-mono text-[10px] uppercase tracking-[0.1em] text-white hover:bg-white/10 hover:text-white"><Link href="/courses">Explore programmes</Link></Button></div></div>
        <div className="reveal-delay relative self-center lg:self-end"><div className="absolute -inset-6 rounded-full bg-[#42B4E7]/10 blur-3xl" /><div className="relative ml-auto max-w-sm border border-[#42B4E7]/45 bg-[#0D1520]/80 p-6 backdrop-blur-md"><div className="flex items-center justify-between"><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#C9C877]">The academy principle</p><PhoenixFlame className="h-7 w-7 text-[#42B4E7]" /></div><p className="mt-10 font-body text-2xl leading-tight text-[#F7F6F2]">Skills that become solutions. Purpose that becomes legacy.</p><div className="mt-10 grid grid-cols-3 border-t border-white/15 pt-4 text-center"><div><p className="font-display text-3xl font-bold text-[#C9C877]">8+</p><p className="mt-1 font-mono text-[8px] uppercase tracking-wider text-white/55">Prep school</p></div><div className="border-x border-white/15"><p className="font-display text-3xl font-bold text-[#C9C877]">6–8</p><p className="mt-1 font-mono text-[8px] uppercase tracking-wider text-white/55">Months guided</p></div><div><p className="font-display text-3xl font-bold text-[#C9C877]">Live</p><p className="mt-1 font-mono text-[8px] uppercase tracking-wider text-white/55">Mentorship</p></div></div></div></div>
      </div>
    </section><PartnerStrip />
    <section id="mandate" className="py-20 sm:py-28"><div className="container grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div className="reveal"><p className="font-mono text-[10px] font-medium uppercase tracking-[0.16em] text-[#8A8835]">{content.mandate_label ?? "Our mandate"}</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">{content.mandate_heading ?? "More than education."}</h2><p className="mt-5 max-w-md font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">{content.mandate_supporting_text ?? "An environment where gifts are discovered, activated, and applied to meaningful work."}</p><div className="mt-8 overflow-hidden rounded-lg border border-[#556970]/15"><img src={MANDATE_IMAGE} alt="PhoennixAI community and mentorship" className="h-56 w-full object-cover transition-transform duration-700 hover:scale-105" /></div></div><div className="reveal-delay self-center border-l-2 border-[#ABA944] pl-7 sm:pl-10"><blockquote className="font-body text-3xl leading-tight text-[#3D4447] dark:text-[#EFF0EA] sm:text-4xl">“{content.mandate ?? "At PhoennixAI, we don't raise followers. We raise leaders and builders. We remind every learner that you're kings, builders, and owners. You're created to create."}”</blockquote><p className="mt-7 font-mono text-[10px] uppercase tracking-[0.13em] text-[#8A8835]">Excellence · Integrity · Impact</p></div></div></section>
    <section className="relative overflow-hidden bg-[#EFF0EA] py-20 dark:bg-white/[0.035] sm:py-28"><div className="container"><div className="reveal flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">Learn by building</p><h2 className="mt-3 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">Practical pathways for every stage.</h2></div><Button asChild variant="outline" className="w-fit rounded-md border-[#556970]/35 font-mono text-[10px] uppercase tracking-[0.1em] text-[#556970] hover:bg-[#556970] hover:text-white dark:border-[#D0DEE1]/45 dark:text-[#D0DEE1] dark:hover:bg-[#D0DEE1] dark:hover:text-[#0D1520]"><Link href="/courses">View all programmes</Link></Button></div><div className="mt-10 grid gap-4 md:grid-cols-3">{courses.filter(course => !course.featured).slice(0, 3).map((course, index) => <article key={course.id} className={`reveal rounded-lg border border-[#556970]/22 bg-white p-6 text-[#1F2426] shadow-sm transition-transform duration-300 hover:-translate-y-1 dark:border-white/12 dark:bg-[#172231] dark:text-[#F7F6F2] ${index === 1 ? "reveal-delay" : index === 2 ? "reveal-delay-2" : ""}`}><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#526269] dark:text-[#AABFC5]">{course.duration}</p><h3 className="mt-7 font-display text-3xl font-bold leading-none tracking-wide">{course.title}</h3><p className="mt-4 font-body leading-7 text-[#425156] dark:text-[#D0DEE1]">{course.description}</p><Link href="/apply" className="mt-7 inline-flex items-center font-mono text-[10px] uppercase tracking-[0.12em] text-[#3E4F55] hover:text-[#1688B8] dark:text-[#C5F0FF] dark:hover:text-white">Explore route</Link></article>)}</div></div></section>
    {featured ? <section className="py-20 sm:py-28"><div className="container grid gap-9 lg:grid-cols-[.8fr_1.2fr]"><div className="reveal flex flex-col justify-center"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">Designed for households</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">A practical start, without the pressure.</h2><p className="mt-5 max-w-sm font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">Our family pathway makes structured learning more accessible while allowing families to retain flexibility.</p><div className="mt-8 overflow-hidden rounded-lg"><img src={PROJECT_IMAGE} alt="Students working on project-led learning" className="h-56 w-full object-cover" /></div></div><div className="reveal-delay"><CourseCard course={featured} /></div></div></section> : null}
    <section id="events" className="relative isolate overflow-hidden bg-[#142833] py-20 text-white sm:py-28"><img src={EVENTS_IMAGE} alt="PhoennixAI Academy event gathering" className="academy-hero-image absolute inset-0 h-full w-full object-cover opacity-28" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(20,40,51,.98)_0%,rgba(20,40,51,.88)_50%,rgba(20,40,51,.48)_100%)]" /><div className="phoenix-grid absolute inset-0" /><div className="container relative grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="reveal"><div className="flex items-center gap-3"><PhoenixFlame className="h-9 w-9 text-[#42B4E7]" /><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#C5F0FF]">Gather, learn, build</p></div><h2 className="mt-5 font-display text-6xl font-bold leading-[.86] tracking-wide sm:text-7xl">Upcoming events.</h2><p className="mt-6 max-w-md font-body text-lg leading-8 text-[#E5F5FA]">Workshops, showcases, and conversations for the next generation of builders. Each event has its own learning purpose and public Luma registration page.</p></div><div className="grid gap-4">{events.length ? events.map(event => <article key={event.id} className="reveal border border-[#42B4E7]/25 bg-[#0D1520]/55 p-6 backdrop-blur-sm"><p className="font-mono text-[10px] uppercase tracking-[0.13em] text-[#A8E6FF]">{event.eventDate}</p><h3 className="mt-5 font-display text-4xl font-bold leading-none tracking-wide">{event.title}</h3><p className="mt-4 max-w-xl font-body text-lg leading-7 text-[#EFF8FB]">{event.summary}</p><a href={event.lumaUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center font-mono text-[10px] uppercase tracking-[0.12em] text-[#A8E6FF] hover:text-white">View event on Luma</a></article>) : <article className="reveal border border-[#42B4E7]/25 bg-[#0D1520]/55 p-6 backdrop-blur-sm"><CalendarDays className="h-7 w-7 text-[#42B4E7]" /><h3 className="mt-5 font-display text-4xl font-bold leading-none tracking-wide">Events are being prepared.</h3><p className="mt-4 max-w-xl font-body text-lg leading-7 text-[#EFF8FB]">The next workshop and showcase will be published here as soon as the Academy team adds it through the Admin Management Centre.</p></article>}</div></div></section>
    <section className="py-20 sm:py-28"><div className="container grid gap-8 lg:grid-cols-[.95fr_1.05fr]"><div className="reveal"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">Innovation in practice</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">Courage to imagine. Discipline to build.</h2><p className="mt-5 max-w-lg font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">This is where learners turn ideas into prototypes, project artefacts, and portfolios. Human creativity, emerging technologies, and guided studio practice make the learning visible and useful.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{[[Compass, "Design thinking", "Rapid prototyping and iteration."],[CheckCircle2, "Portfolio outcomes", "Ideas shaped into real work."]].map(([Icon, title, copy]) => { const IconComponent = Icon as typeof Compass; return <div key={title as string} className="border-t border-[#556970]/20 pt-4"><IconComponent className="h-5 w-5 text-[#42B4E7]" /><h3 className="mt-4 font-display text-2xl font-bold tracking-wide">{title as string}</h3><p className="mt-2 font-body text-[#526269] dark:text-[#B3B9BA]">{copy as string}</p></div>})}</div></div><figure className="reveal-delay overflow-hidden rounded-lg border border-[#556970]/15"><img src={INNOVATION_IMAGE} alt="Learners collaborating around a laptop during a PhoennixAI Academy studio session" className="h-full min-h-80 w-full object-cover" /><figcaption className="border-t border-[#556970]/15 bg-[#EFF0EA] px-4 py-3 font-body text-sm leading-6 text-[#526269] dark:bg-white/[0.04] dark:text-[#D0DEE1]"><span className="font-semibold text-[#1688B8]">Studio practice in action:</span> collaborative learning, project critique, and the practical work behind a portfolio outcome.</figcaption></figure></div></section>
  </main><VisitorChat /></div>;
}
