import { ArrowUpRight, BriefcaseBusiness, CalendarDays, Mic2, Rocket, Sparkles, UsersRound } from "lucide-react";
import { Link } from "wouter";
import AcademyHeader from "@/components/AcademyHeader";
import PhoenixFlame from "@/components/PhoenixFlame";
import { Button } from "@/components/ui/button";

type ArchiveCard = { title: string; label: string; description: string; icon: typeof UsersRound; className: string; tone: string };

const archiveCards: ArchiveCard[] = [
  { title: "Alumni in action", label: "Future archive", description: "A reserved space for alumni milestones, first launches, and the work they build after the Academy.", icon: UsersRound, className: "md:col-span-2 md:row-span-2", tone: "from-[#0D2940] via-[#173B56] to-[#42B4E7]/35" },
  { title: "Founder rooms", label: "Community sessions", description: "Founder and start-up gatherings where builders meet practical peers and collaborators.", icon: Rocket, className: "md:col-span-1", tone: "from-[#343B19] via-[#56601C] to-[#ABA944]/50" },
  { title: "Capital conversations", label: "VC, Angel & grants", description: "A place for investor conversations, grant-institute talks, and candid capital-readiness learning.", icon: Mic2, className: "md:col-span-1", tone: "from-[#172231] via-[#263D52] to-[#1688B8]/45" },
  { title: "Gala and recognition", label: "Academy moments", description: "Future gala photographs, achievement evenings, and moments worth remembering together.", icon: Sparkles, className: "md:col-span-1", tone: "from-[#352B3B] via-[#5C4265] to-[#C9C877]/45" },
  { title: "Retreats and horizons", label: "Builder wellbeing", description: "A dedicated home for retreats, shared learning journeys, and the spaces between the work.", icon: CalendarDays, className: "md:col-span-2", tone: "from-[#142833] via-[#1F4B49] to-[#42B4E7]/35" },
  { title: "Agency field notes", label: "PhoennixAI Agency", description: "Technology, automation, and innovation moments from the agency practice that informs the Academy.", icon: BriefcaseBusiness, className: "md:col-span-1", tone: "from-[#1C2431] via-[#364D68] to-[#42B4E7]/45" },
];

export default function InMotion() {
  return <div className="min-h-screen bg-[#F7F6F2] text-[#1F2426] dark:bg-[#0D1520] dark:text-[#F7F6F2]"><AcademyHeader /><main>
    <section className="relative isolate overflow-hidden bg-[#0D1520] py-20 text-white sm:py-28"><div className="phoenix-grid absolute inset-0 opacity-60" /><div className="absolute -left-24 top-8 h-80 w-80 rounded-full border border-[#42B4E7]/25" /><div className="absolute -bottom-40 right-[12%] h-96 w-96 rounded-full bg-[#42B4E7]/10 blur-[110px]" /><div className="container relative grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><div className="flex items-center gap-3"><PhoenixFlame className="h-9 w-9 text-[#42B4E7]" /><p className="font-mono text-[10px] uppercase tracking-[0.17em] text-[#C5F0FF]">The Builder Archive</p></div><h1 className="mt-7 max-w-4xl font-display text-7xl font-bold leading-[.84] tracking-wide sm:text-8xl">In <span className="text-[#C9C877]">Motion.</span></h1><p className="mt-7 max-w-2xl font-body text-xl leading-8 text-[#E5F5FA]">A living visual archive for alumni moments, founder gatherings, capital conversations, retreats, and the people building meaningful impact across technology and business.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="rounded-md bg-[#ABA944] px-5 font-mono text-[10px] uppercase tracking-[0.1em] text-[#1F2426] hover:bg-[#C9C877]"><Link href="/apply">Join the community</Link></Button><Button asChild size="lg" variant="outline" className="rounded-md border-white/25 bg-white/5 font-mono text-[10px] uppercase tracking-[0.1em] text-white hover:bg-white/10 hover:text-white"><Link href="/courses">Explore programmes</Link></Button></div></div><div className="self-end border border-[#42B4E7]/30 bg-[#142833]/80 p-6 backdrop-blur-md"><p className="font-mono text-[9px] uppercase tracking-[0.15em] text-[#C9C877]">Growing with the community</p><p className="mt-7 font-display text-4xl font-bold leading-tight tracking-wide">Every photograph will become a record of momentum.</p><p className="mt-4 font-body leading-7 text-[#D2E6EF]">This archive is currently prepared for authentic community imagery. Future entries will be added from Academy and partner events, never fabricated.</p></div></div></section>
    <section className="py-18 sm:py-24"><div className="container"><div className="max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">Built for real moments</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">A bento archive that grows with the work.</h2><p className="mt-5 font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">The page is structured to accommodate event photography, short editorial captions, collaborator highlights, and evolving programmes without losing its clarity or sense of craft.</p></div><div className="mt-10 grid auto-rows-[180px] gap-4 md:grid-cols-3"><div className="group relative overflow-hidden rounded-lg bg-[#0D1520] p-6 text-white md:col-span-1"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(66,180,231,.28),transparent_38%)]" /><PhoenixFlame className="relative h-10 w-10 text-[#42B4E7]" /><p className="relative mt-14 font-display text-3xl font-bold tracking-wide">Archive ready</p><p className="relative mt-2 font-body text-sm text-[#C5F0FF]">Placeholders will become authentic visual stories.</p></div>{archiveCards.map(({ title, label, description, icon: Icon, className, tone }) => <article key={title} className={`group relative overflow-hidden rounded-lg bg-gradient-to-br ${tone} p-6 text-white ${className}`}><div className="absolute inset-0 bg-[#08131d]/25 transition-colors duration-300 group-hover:bg-transparent" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-start justify-between"><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#E5F5FA]">{label}</p><Icon className="h-5 w-5 text-[#C5F0FF]" /></div><div><h3 className="font-display text-4xl font-bold leading-none tracking-wide">{title}</h3><p className="mt-3 max-w-md font-body leading-6 text-[#E5F5FA]">{description}</p></div></div></article>)}</div></div></section>
    <section className="border-y border-[#556970]/14 bg-[#EFF0EA] py-16 dark:bg-white/[0.035]"><div className="container flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">For builders and partners</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide">Have a moment that belongs in the archive?</h2><p className="mt-5 font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">As the community grows, the archive can feature approved partner events, alumni milestones, and moments that reflect the Academy’s work in the real world.</p></div><Button asChild className="w-fit rounded-md bg-[#556970] px-5 font-mono text-[10px] uppercase tracking-[0.1em] text-white hover:bg-[#3E4F55]"><Link href="/apply">Start a conversation</Link></Button></div></section>
  </main></div>;
}
