import { BadgeCheck, ChevronDown, Compass, GraduationCap, Landmark, Rocket, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";
import AcademyHeader from "@/components/AcademyHeader";
import PhoenixFlame from "@/components/PhoenixFlame";
import { Button } from "@/components/ui/button";

const pathways = [
  { icon: Compass, title: "Junior Tech Explorer", audience: "Ages 8 to 15", copy: "A CPD-approved foundational recognition for younger learners developing practical confidence in product design, coding, and gaming." },
  { icon: BadgeCheck, title: "Certified Professional", audience: "Adults", copy: "A CPD-approved career-focused recognition for adult learners developing capability in AI Automation, Content Creation, and Digital Marketing." },
  { icon: Rocket, title: "Founder & Venture Graduate", audience: "Entrepreneurial Club", copy: "A CPD-approved programme recognition for members who complete the investor-readiness pipeline and founder development journey." },
];

const modules = [
  ["01", "Introduction", "Understand the programme journey, the investor-readiness process, and the foundations for a focused capital-raising strategy."],
  ["02", "Deciphering the Investment World", "Learn the language of investment, common capital sources, investor expectations, and the context in which funding decisions are made."],
  ["03", "Analyzing My Business Feasibility Objectively", "Assess the business opportunity, market, assumptions, strengths, risks, and evidence with disciplined objectivity."],
  ["04", "Structuring and Incorporating Your Company", "Consider suitable company structures and incorporation foundations for the venture’s stage, ambition, and investor readiness."],
  ["05", "Building a Financial Model and Projections", "Develop financial projections and a model that support credible planning, funding conversations, and decision making."],
  ["06", "Building Your Team", "Identify the people, roles, advisors, and capabilities required to build confidence in the venture and its execution."],
  ["07", "Creating an Executive Summary: Less Is More", "Create a concise executive summary that communicates the opportunity, traction, vision, and investment case with clarity."],
  ["08", "Creating an Impactful and Compelling Pitch Deck", "Develop a pitch deck that presents the problem, solution, market, strategy, and financial potential with focus and impact."],
  ["09", "Key Steps to Developing Your Business Plan", "Bring the essential components into a practical business plan that aligns operational direction with commercial ambition."],
  ["10", "Legal and Compliance Readiness", "Prepare for the legal, governance, and compliance considerations that investors expect a well-prepared founder to address."],
  ["11", "Structuring Your Offering for Investors", "Shape an investment offering that aligns with the company’s stage, financial needs, direction, and investment proposition."],
  ["12", "Presenting Your Business and Investment Opportunity", "Present the business and investment case with confidence, evidence, and a coherent narrative that supports investor engagement."],
  ["13", "Navigating Investment Challenges", "Anticipate common questions, objections, funding challenges, and practical steps that can strengthen the investment case."],
  ["14", "Post-Investment Relations & Growth", "Understand investor relationships, reporting discipline, and the growth responsibilities that continue after investment."],
  ["15", "Conclusions & Moving Forward", "Turn the programme into a clear action plan for your next fundraising, investor-engagement, and business-growth steps."],
];

const outcomes = [
  "Build investment readiness through financial projections, market research, and legal-compliance awareness.",
  "Identify and address potential risks so the business can become a more attractive investment proposition.",
  "Create documents and presentations that flow clearly and create interest with investors.",
  "Develop funding strategies aligned to business stage, industry, and investment requirements.",
  "Build and leverage a network of private and institutional investors over time.",
  "Stand out in a competitive fundraising landscape with practical knowledge and founder tools.",
];

export default function RiseToCapital() {
  return <div className="min-h-screen bg-[#F7F6F2] text-[#1F2426] dark:bg-[#0D1520] dark:text-[#F7F6F2]"><AcademyHeader /><main>
    <section className="relative isolate overflow-hidden bg-[#142833] py-20 text-white sm:py-28"><div className="phoenix-grid absolute inset-0 opacity-80" /><div className="absolute -right-12 top-12 h-96 w-96 rounded-full border border-[#42B4E7]/25" /><div className="absolute bottom-0 left-[35%] h-72 w-72 rounded-full bg-[#42B4E7]/10 blur-[100px]" /><div className="container relative grid gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><div className="flex items-center gap-3"><PhoenixFlame className="h-9 w-9 text-[#42B4E7]" /><p className="font-mono text-[10px] font-medium uppercase tracking-[0.16em] text-[#C5F0FF]">In collaboration with Conquest Capital Advisors</p></div><h1 className="mt-7 max-w-4xl font-display text-6xl font-bold leading-[.84] tracking-wide sm:text-8xl">Rise to <span className="text-[#C9C877]">Capital.</span></h1><p className="mt-7 max-w-2xl font-body text-xl leading-8 text-[#E5F5FA]">PhoennixAI and Conquest Capital Advisors have collaborated to offer advanced entrepreneur and capital-readiness training. Developed by Mr Papadoyianis, Rise to Capital provides practical insight into the step-by-step process of business feasibility and fundraising.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="rounded-md bg-[#ABA944] px-5 font-mono text-[10px] uppercase tracking-[0.1em] text-[#1F2426] hover:bg-[#C9C877]"><Link href="/apply">Start a conversation</Link></Button><a href="#curriculum" className="inline-flex items-center rounded-md border border-white/20 px-5 py-3 font-mono text-[10px] uppercase tracking-[0.1em] text-white transition-colors hover:border-[#42B4E7] hover:bg-[#42B4E7]/10">Explore modules</a></div></div><div className="self-end border border-[#42B4E7]/30 bg-[#0D1520]/70 p-6 backdrop-blur-md"><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#C9C877]">Programme approach</p><p className="mt-7 font-display text-4xl font-bold leading-tight tracking-wide">Founder mindset meets practical capital readiness.</p><div className="mt-8 grid grid-cols-2 gap-px bg-white/15"><div className="bg-[#142833] p-4"><Landmark className="h-5 w-5 text-[#42B4E7]" /><p className="mt-3 font-body text-sm text-[#E5F5FA]">Business feasibility and fundraising preparation</p></div><div className="bg-[#142833] p-4"><UsersRound className="h-5 w-5 text-[#42B4E7]" /><p className="mt-3 font-body text-sm text-[#E5F5FA]">Conquest Capital Advisors partner learning</p></div></div></div></div></section>
    <section className="bg-[#EFF0EA] py-16 dark:bg-white/[0.035] sm:py-20"><div className="container"><div className="max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">What you will gain</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">Become ready to make the right capital conversation.</h2><p className="mt-5 font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">Through the fifteen modules, you will gain a deep understanding of the preparation, structure, and fundraising process for a conceptual, start-up, or operating business.</p></div><div className="mt-9 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{outcomes.map((outcome, index) => <article key={outcome} className="border-l-2 border-[#42B4E7] bg-white p-5 shadow-sm dark:bg-[#172231]"><p className="font-display text-2xl font-bold text-[#42B4E7]/70">0{index + 1}</p><p className="mt-4 font-body leading-7 text-[#526269] dark:text-[#D0DEE1]">{outcome}</p></article>)}</div></div></section>
    <section id="curriculum" className="py-20 sm:py-28"><div className="container"><div className="max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">15-module public curriculum</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">A transparent pathway from idea to readiness.</h2><p className="mt-5 font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">Select a module to explore its high-level focus. Together, the sequence details the components and techniques required to become investor-ready.</p></div><div className="mt-12 grid gap-3 lg:grid-cols-2">{modules.map(([number, title, copy], index) => <details key={number} open={index === 0} className="group rounded-lg border border-[#556970]/18 bg-white shadow-sm transition-colors open:border-[#42B4E7]/45 dark:bg-[#172231]"><summary className="flex cursor-pointer list-none items-center gap-4 p-5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#42B4E7]/55"><span className="font-display text-3xl font-bold text-[#42B4E7]/65">{number}</span><span className="min-w-0 flex-1"><span className="block font-display text-3xl font-bold leading-none tracking-wide">{title}</span><span className="mt-1.5 block font-mono text-[9px] uppercase tracking-[0.11em] text-[#8A8835]">Select to view module focus</span></span><ChevronDown className="h-5 w-5 shrink-0 text-[#1688B8] transition-transform duration-200 group-open:rotate-180" /></summary><div className="border-t border-[#556970]/14 px-5 pb-5 pt-4"><p className="max-w-xl font-body leading-7 text-[#526269] dark:text-[#D0DEE1]">{copy}</p></div></details>)}</div></div></section>
    <section id="pathways" className="bg-[#EFF0EA] py-20 dark:bg-white/[0.035] sm:py-28"><div className="container"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">PhoennixAI certification pathways</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">Recognition for every stage of the journey.</h2><p className="mt-5 font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">All PhoennixAI Academy certificates are CPD approved and matched to the learner’s age, professional direction, and venture-development pathway.</p></div><div className="space-y-4">{pathways.map(({ icon: Icon, title, audience, copy }) => <article key={title} className="group flex gap-5 rounded-lg border border-[#556970]/18 bg-white p-6 transition-transform duration-200 hover:-translate-y-1 dark:bg-[#172231]"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-md bg-[#42B4E7]/12 text-[#1688B8]"><Icon className="h-5 w-5" /></div><div><p className="font-mono text-[9px] uppercase tracking-[0.13em] text-[#8A8835]">{audience}</p><h3 className="mt-2 font-display text-3xl font-bold tracking-wide">{title}</h3><p className="mt-2 font-body leading-7 text-[#526269] dark:text-[#D0DEE1]">{copy}</p></div></article>)}</div></div></div></section>
    <section className="py-20 sm:py-28"><div className="container grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-lg border border-[#42B4E7]/25 bg-[#142833] p-8 text-white sm:p-10"><div className="flex items-center gap-3"><ShieldCheck className="h-7 w-7 text-[#42B4E7]" /><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#C5F0FF]">Professional progression</p></div><h2 className="mt-7 font-display text-5xl font-bold leading-none tracking-wide">Build credibility with care.</h2><div className="mt-7 grid gap-5 font-body leading-7 text-[#E5F5FA]"><p><strong className="text-[#C9C877]">CPD-approved certification:</strong> All PhoennixAI Academy certificates are CPD approved and issued as recognition of programme completion.</p><p><strong className="text-[#C9C877]">Rise to Capital professional recognition:</strong> Programme recognition acknowledges learning and participation within the Conquest Capital Advisors partner framework.</p><p><strong className="text-[#C9C877]">Investor-network progression:</strong> Eligible participants will be introduced to relevant peer-reviewed Angels and VCs through approved partner processes. Access, introductions, and investment outcomes are not guaranteed.</p></div></div><div className="flex flex-col justify-center border-l-2 border-[#ABA944] pl-7 sm:pl-10"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#8A8835]">Interested in Rise to Capital?</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide">Let’s map the right pathway.</h2><p className="mt-5 font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">Start with a conversation about your stage, venture direction, and the best next learning step.</p><Button asChild size="lg" className="mt-8 w-fit rounded-md bg-[#556970] px-5 font-mono text-[10px] uppercase tracking-[0.1em] text-white hover:bg-[#3E4F55]"><Link href="/apply">Make an enquiry</Link></Button></div></div></section>
  </main></div>;
}
