import { BadgeCheck, Compass, GraduationCap, Landmark, Rocket, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";
import AcademyHeader from "@/components/AcademyHeader";
import PhoenixFlame from "@/components/PhoenixFlame";
import { Button } from "@/components/ui/button";

const pathways = [
  { icon: Compass, title: "Junior Tech Explorer", audience: "Ages 8 to 15", copy: "A foundational recognition for younger learners developing practical confidence in product design, coding, and gaming." },
  { icon: BadgeCheck, title: "Certified Professional", audience: "Adults", copy: "A career-focused recognition for adult learners developing capability in AI Automation, Content Creation, and Digital Marketing." },
  { icon: Rocket, title: "Founder & Venture Graduate", audience: "Entrepreneurial Club", copy: "A programme recognition for members who complete the investor-readiness pipeline and founder development journey." },
];

const modules = [
  ["01", "Founder clarity", "Define the problem, customer, proposition, and founder narrative that make an early-stage venture understandable."],
  ["02", "Capital readiness", "Build the core materials and commercial thinking needed to prepare thoughtfully for capital conversations."],
  ["03", "Investor communication", "Practice the clarity, confidence, evidence, and storytelling that help investors assess an opportunity."],
  ["04", "Venture next steps", "Create an action plan for continued founder growth, commercial validation, and the appropriate next conversation."],
];

export default function RiseToCapital() {
  return <div className="min-h-screen bg-[#F7F6F2] text-[#1F2426] dark:bg-[#0D1520] dark:text-[#F7F6F2]"><AcademyHeader /><main>
    <section className="relative isolate overflow-hidden bg-[#142833] py-20 text-white sm:py-28"><div className="phoenix-grid absolute inset-0 opacity-80" /><div className="absolute -right-12 top-12 h-96 w-96 rounded-full border border-[#42B4E7]/25" /><div className="absolute bottom-0 left-[35%] h-72 w-72 rounded-full bg-[#42B4E7]/10 blur-[100px]" /><div className="container relative grid gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><div className="flex items-center gap-3"><PhoenixFlame className="h-9 w-9 text-[#42B4E7]" /><p className="font-mono text-[10px] font-medium uppercase tracking-[0.16em] text-[#C5F0FF]">Partner-led programme</p></div><h1 className="mt-7 max-w-4xl font-display text-6xl font-bold leading-[.84] tracking-wide sm:text-8xl">Rise to <span className="text-[#C9C877]">Capital.</span></h1><p className="mt-7 max-w-2xl font-body text-xl leading-8 text-[#E5F5FA]">A structured founder and investor-readiness pathway for learners ready to develop their ideas, commercial confidence, and venture conversations.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="rounded-md bg-[#ABA944] px-5 font-mono text-[10px] uppercase tracking-[0.1em] text-[#1F2426] hover:bg-[#C9C877]"><Link href="/apply">Start a conversation</Link></Button><a href="#pathways" className="inline-flex items-center rounded-md border border-white/20 px-5 py-3 font-mono text-[10px] uppercase tracking-[0.1em] text-white transition-colors hover:border-[#42B4E7] hover:bg-[#42B4E7]/10">Explore pathways</a></div></div><div className="self-end border border-[#42B4E7]/30 bg-[#0D1520]/70 p-6 backdrop-blur-md"><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#C9C877]">Programme approach</p><p className="mt-7 font-display text-4xl font-bold leading-tight tracking-wide">Founder mindset meets practical capital readiness.</p><div className="mt-8 grid grid-cols-2 gap-px bg-white/15"><div className="bg-[#142833] p-4"><Landmark className="h-5 w-5 text-[#42B4E7]" /><p className="mt-3 font-body text-sm text-[#E5F5FA]">Venture and investor preparation</p></div><div className="bg-[#142833] p-4"><UsersRound className="h-5 w-5 text-[#42B4E7]" /><p className="mt-3 font-body text-sm text-[#E5F5FA]">Partner-led learning community</p></div></div></div></div></section>
    <section className="py-20 sm:py-28"><div className="container"><div className="max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">Public curriculum overview</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">A transparent pathway from idea to readiness.</h2><p className="mt-5 font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">The public overview explains the direction and outcomes of Rise to Capital. Detailed delivery materials, founder templates, and partner resources are shared through the programme and individual conversations.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-lg border border-[#556970]/18 bg-[#556970]/18 md:grid-cols-2">{modules.map(([number, title, copy]) => <article key={number} className="bg-white p-7 dark:bg-[#172231]"><p className="font-display text-5xl font-bold text-[#42B4E7]/55">{number}</p><h3 className="mt-8 font-display text-3xl font-bold tracking-wide">{title}</h3><p className="mt-3 max-w-md font-body leading-7 text-[#526269] dark:text-[#D0DEE1]">{copy}</p></article>)}</div></div></section>
    <section id="pathways" className="bg-[#EFF0EA] py-20 dark:bg-white/[0.035] sm:py-28"><div className="container"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#8A8835]">PhoennixAI certification pathways</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide sm:text-6xl">Recognition for every stage of the journey.</h2><p className="mt-5 font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">Certificate tiers match the learner’s age, professional direction, and venture-development pathway.</p></div><div className="space-y-4">{pathways.map(({ icon: Icon, title, audience, copy }) => <article key={title} className="group flex gap-5 rounded-lg border border-[#556970]/18 bg-white p-6 transition-transform duration-200 hover:-translate-y-1 dark:bg-[#172231]"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-md bg-[#42B4E7]/12 text-[#1688B8]"><Icon className="h-5 w-5" /></div><div><p className="font-mono text-[9px] uppercase tracking-[0.13em] text-[#8A8835]">{audience}</p><h3 className="mt-2 font-display text-3xl font-bold tracking-wide">{title}</h3><p className="mt-2 font-body leading-7 text-[#526269] dark:text-[#D0DEE1]">{copy}</p></div></article>)}</div></div></div></section>
    <section className="py-20 sm:py-28"><div className="container grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-lg border border-[#42B4E7]/25 bg-[#142833] p-8 text-white sm:p-10"><div className="flex items-center gap-3"><ShieldCheck className="h-7 w-7 text-[#42B4E7]" /><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#C5F0FF]">Professional progression</p></div><h2 className="mt-7 font-display text-5xl font-bold leading-none tracking-wide">Build credibility with care.</h2><div className="mt-7 grid gap-5 font-body leading-7 text-[#E5F5FA]"><p><strong className="text-[#C9C877]">CPD route:</strong> A potential independent approval pathway for business, technology, and corporate learning. CPD certification can only be referenced once independent approval has been granted.</p><p><strong className="text-[#C9C877]">Rise to Capital professional recognition:</strong> Programme recognition can acknowledge learning and participation according to the final partner framework.</p><p><strong className="text-[#C9C877]">Investor-network progression:</strong> Eligible participants may be introduced to relevant peer-reviewed Angels and VCs through approved partner processes. Access, introductions, and investment outcomes are not guaranteed.</p></div></div><div className="flex flex-col justify-center border-l-2 border-[#ABA944] pl-7 sm:pl-10"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#8A8835]">Interested in Rise to Capital?</p><h2 className="mt-4 font-display text-5xl font-bold leading-none tracking-wide">Let’s map the right pathway.</h2><p className="mt-5 font-body text-lg leading-8 text-[#526269] dark:text-[#B3B9BA]">Start with a conversation about your stage, venture direction, and the best next learning step.</p><Button asChild size="lg" className="mt-8 w-fit rounded-md bg-[#556970] px-5 font-mono text-[10px] uppercase tracking-[0.1em] text-white hover:bg-[#3E4F55]"><Link href="/apply">Make an enquiry</Link></Button></div></div></section>
  </main></div>;
}
