import { Menu, Moon, Sun } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { useTheme } from "@/contexts/ThemeContext";

const PHOENIX_LOGO = "/manus-storage/phoennixai-phoenix-logo_7d43347d.jpg";

export default function AcademyHeader() {
  const { theme, toggleTheme } = useTheme();
  return <header className="sticky top-0 z-40 border-b border-[#556970]/15 bg-[#F7F6F2]/92 backdrop-blur-xl dark:border-white/10 dark:bg-[#0D1520]/92"><div className="container flex h-16 items-center justify-between gap-4"><Link href="/" className="group flex items-center gap-3"><span className="relative grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-full border-2 border-[#42B4E7]/75 bg-[#0D1520] shadow-[0_0_0_3px_rgba(66,180,231,.08)] transition-transform duration-200 group-hover:scale-105"><img src={PHOENIX_LOGO} alt="PhoennixAI phoenix" className="h-full w-full scale-[1.35] object-cover object-[50%_28%]" /></span><span className="leading-none"><strong className="font-display text-xl font-bold tracking-wide text-[#1F2426] dark:text-[#F7F6F2]">Phoenn<span className="text-[#1688B8]">ix</span>AI</strong><span className="mt-0.5 block font-mono text-[8px] font-medium uppercase tracking-[0.13em] text-[#526269]">Academy</span></span></Link><nav className="hidden items-center gap-7 font-mono text-[10px] uppercase tracking-[0.12em] text-[#556970] md:flex"><Link href="/" className="transition-colors hover:text-[#1688B8]">Home</Link><Link href="/courses" className="transition-colors hover:text-[#1688B8]">Programmes</Link><a href="/#events" className="transition-colors hover:text-[#1688B8]">Events</a><a href="/#mandate" className="transition-colors hover:text-[#1688B8]">Our mandate</a></nav><div className="flex items-center gap-1.5"><Button variant="ghost" size="icon" aria-label="Toggle colour theme" onClick={toggleTheme} className="h-9 w-9 rounded-full text-[#556970] hover:bg-[#EFF0EA] hover:text-[#3E4F55] dark:text-[#F7F6F2]">{theme === "dark" ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}</Button><Button asChild className="hidden rounded-md bg-[#556970] px-4 font-mono text-[10px] font-medium uppercase tracking-[0.08em] text-white hover:bg-[#3E4F55] sm:inline-flex"><Link href="/apply">Begin enquiry</Link></Button><Button asChild size="icon" variant="ghost" className="md:hidden"><Link href="/courses" aria-label="Browse programmes"><Menu className="h-5 w-5" /></Link></Button></div></div></header>;
}
