import { Facebook, Instagram, Linkedin, MapPin, Twitter } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

const PHOENIX_LOGO = "/manus-storage/phoennixai-phoenix-logo_7d43347d.jpg";

function SocialLink({ href, label, icon: Icon }: { href?: string; label: string; icon: typeof Instagram }) { return <a href={href || "#"} onClick={event => { if (!href) event.preventDefault(); }} aria-label={label} title={href ? label : `${label} link can be added in Admin`} className="group grid h-9 w-9 place-items-center rounded-md border border-[#556970]/20 text-[#526269] transition-[transform,color,background-color,border-color,box-shadow] duration-200 hover:-translate-y-1 hover:scale-110 hover:border-[#42B4E7] hover:bg-[#42B4E7]/15 hover:text-[#1688B8] hover:shadow-[0_8px_18px_rgba(66,180,231,.2)] focus-visible:-translate-y-1 focus-visible:scale-110 focus-visible:border-[#42B4E7] focus-visible:bg-[#42B4E7]/15 focus-visible:text-[#1688B8] focus-visible:shadow-[0_0_0_3px_rgba(66,180,231,.25)] focus-visible:outline-none dark:text-[#D1E8EF]"><Icon className="h-4 w-4 transition-transform duration-200 group-hover:rotate-[-8deg] group-focus-visible:rotate-[-8deg]" /></a>; }

export default function AcademyFooter() {
  const { data } = trpc.academy.catalog.useQuery(undefined, { refetchInterval: 15000 }); const content = data?.content ?? {}; const [purpose, signature] = (content.footer_purpose ?? "Purpose-led learning for future builders, leaders, and innovators.\nYou’re Created to Create.").split("\n");
  return <footer data-academy-footer className="border-t border-[#556970]/15 bg-white py-14 text-[#3D4447] dark:bg-[#0D1520] dark:text-[#EFF0EA]"><div className="container grid gap-10 md:grid-cols-[1.25fr_.8fr_.9fr]"><div><div className="flex items-center gap-3"><span className="grid h-11 w-11 overflow-hidden rounded-full border-2 border-[#42B4E7]/70 bg-[#0D1520]"><img src={PHOENIX_LOGO} alt="PhoennixAI phoenix" className="h-full w-full scale-[1.35] object-cover object-[50%_28%]" /></span><div><p className="font-display text-3xl font-bold tracking-wide">Phoenn<span className="text-[#1688B8]">ix</span>AI</p><p className="mt-0.5 font-mono text-[9px] uppercase tracking-[0.13em] text-[#526269] dark:text-[#B3C1C5]">Academy</p></div></div><p className="mt-5 max-w-sm whitespace-pre-line font-body leading-7 text-[#526269] dark:text-[#B3B9BA]">{purpose}{signature ? <><br /><span className="font-semibold text-[#1688B8] dark:text-[#A8E6FF]">{signature}</span></> : null}</p><div className="mt-6 flex gap-2"><SocialLink label="Instagram" href={content.social_instagram} icon={Instagram} /><SocialLink label="LinkedIn" href={content.social_linkedin} icon={Linkedin} /><SocialLink label="X" href={content.social_x} icon={Twitter} /><SocialLink label="Facebook" href={content.social_facebook} icon={Facebook} /></div></div><div><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#8A8835]">Navigate</p><nav aria-label="Footer navigation" className="mt-4 grid gap-2.5 font-body"><Link href="/" className="hover:text-[#1688B8]">Home</Link><Link href="/courses" className="hover:text-[#1688B8]">Programmes</Link><Link href="/curriculum" className="hover:text-[#1688B8]">Curriculum &amp; capability</Link><Link href="/rise-to-capital" className="hover:text-[#1688B8]">Rise to Capital</Link><Link href="/apply" className="hover:text-[#1688B8]">Student enquiry</Link><Link href="/#events" className="hover:text-[#1688B8]">Events</Link></nav></div><div><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#8A8835]">Contact</p><div className="mt-4 space-y-3 font-body text-[#526269] dark:text-[#B3B9BA]"><p className="flex gap-2"><MapPin className="mt-1 h-4 w-4 shrink-0 text-[#42B4E7]" />{content.footer_address ?? "58 Peregrine Road, Essex, IG6 3SZ"}</p><a className="block hover:text-[#1688B8]" href={`mailto:${content.footer_email ?? "info@phoennixai.com"}`}>{content.footer_email ?? "info@phoennixai.com"}</a><p>{content.footer_hours ?? "Mon–Fri · 08:00–18:00 UK Time"}</p></div></div></div><div className="container mt-12 border-t border-[#556970]/15 pt-5 font-mono text-[8px] uppercase tracking-[0.12em] text-[#9BA4A7]">© {new Date().getFullYear()} PhoennixAI. All rights reserved.</div></footer>;
}
