import { CheckCircle2 } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import PhoenixFlame from "@/components/PhoenixFlame";

export type CatalogCourse = { id: number; title: string; description: string; duration: string; pricePence: number; paymentLink: string | null; featured: number };
export const formatPrice = (pricePence: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(pricePence / 100);

export default function CourseCard({ course }: { course: CatalogCourse }) {
  const featured = Boolean(course.featured);
  return <article className={`relative flex h-full flex-col overflow-hidden rounded-lg border p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl ${featured ? "border-[#42B4E7]/45 bg-[#203641] text-[#F7F6F2] shadow-lg shadow-[#203641]/15" : "border-[#556970]/22 bg-white text-[#1F2426] shadow-sm dark:bg-[#172231] dark:text-[#F7F6F2]"}`}><div className="absolute right-0 top-0 h-24 w-24 rounded-bl-full bg-[#42B4E7]/10" />{featured && <div className="relative mb-6 flex w-fit items-center gap-1.5 rounded-full bg-[#42B4E7]/15 px-3 py-1 font-mono text-[9px] font-bold uppercase tracking-[0.1em] text-[#C5F0FF]"><PhoenixFlame className="h-3.5 w-3.5 text-[#42B4E7]" />Household value</div>}<div className="relative mb-6"><p className={`font-mono text-[9px] uppercase tracking-[0.14em] ${featured ? "text-[#A8E6FF]" : "text-[#526269] dark:text-[#AABFC5]"}`}>{course.duration}</p><h3 className="mt-3 font-display text-3xl font-bold leading-none tracking-wide">{course.title}</h3><p className={`mt-4 font-body text-[15px] leading-6 ${featured ? "text-[#F3F7F8]" : "text-[#425156] dark:text-[#D0DEE1]"}`}>{course.description}</p></div><div className="relative mt-auto"><div className="flex items-end gap-2"><span className="font-display text-4xl font-bold">{formatPrice(course.pricePence)}</span><span className={`mb-1.5 font-mono text-[10px] ${featured ? "text-[#A8E6FF]" : "text-[#526269] dark:text-[#AABFC5]"}`}>PER MONTH</span></div><div className="mt-6 flex flex-wrap gap-2"><Button asChild className={featured ? "rounded-md bg-[#ABA944] text-[#1F2426] hover:bg-[#C9C877]" : "rounded-md bg-[#556970] text-white hover:bg-[#3E4F55]"}><Link href="/apply">Enquire</Link></Button>{course.paymentLink ? <Button asChild variant="outline" className={featured ? "border-white/30 text-white hover:bg-white/10 hover:text-white" : "border-[#556970]/35 text-[#425156] hover:bg-[#EFF0EA] dark:border-[#AABFC5]/50 dark:text-[#E6F0F2] dark:hover:bg-white/10"}><a href={course.paymentLink} target="_blank" rel="noreferrer">Payment link <CheckCircle2 className="ml-1.5 h-4 w-4" /></a></Button> : null}</div></div></article>;
}
